name: Build Windows App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: 'stable'

    - name: Install dependencies
      run: flutter pub get

    - name: Build Windows application
      run: flutter build windows

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: windows-build
        path: build/windows/runner/Release/
