name: Build Windows App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3 # Updated to v3 for Node.js 20

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.3' # Use 'latest' to get the most recent version

    - name: Install dependencies
      run: flutter pub get

    - name: Build Windows application
      run: flutter build windows

    - name: List build directory
      run: dir build/windows/runner/Release/

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3 # Updated to v3 for Node.js 20
      with:
        name: windows-build
        path: build/windows/runner/Release/
